### ISSUE TITLE
bing-wall --set ERRORS...

### ISSUE THREAD

**Issue by cvbasta75** [keshavbhatt/BingWall#11]
On Ubuntu Desktop 20.04 I get the follwing errors:
`Gtk-Message: 09:00:59.352: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:00:59.354: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.77\" (uid=1000 pid=2433 comm=\"bing-wall --set \" label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=725 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.77\" (uid=1000 pid=2433 comm=\"bing-wall --set \" label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=725 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"
`

**Comment by keshavbhatt** [comment]
These errors are normal, and will not affect application's functionality.

**Comment by omerasif57** [comment]
`label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.NetworkManager\"` 

This error seems to be due to bing-wall snap permission of network manager. 
once I mark permission within snap store, these error gone but some other error show up and wallpaper is not being set. 

> (bing-wall:11157): Gtk-WARNING **: 16:36:12.956: Theme parsing error: gtk.css:1555:23: 'font-feature-settings' is not a valid property name
> 
> (bing-wall:11157): Gtk-WARNING **: 16:36:12.960: Theme parsing error: gtk.css:3591:25: 'font-feature-settings' is not a valid property name
> 
> (bing-wall:11157): Gtk-WARNING **: 16:36:12.961: Theme parsing error: gtk.css:4053:23: 'font-feature-settings' is not a valid property name
> Gtk-Message: 16:36:12.991: Failed to load module "canberra-gtk-module"
> Gtk-Message: 16:36:12.993: Failed to load module "canberra-gtk-module"
> Qt: Session management error: Could not open network socket
> QApplication: invalid style override passed, ignoring it.


btw is it a 32 bit application? 
I am on fresh install Ubuntu 20.04.1 release. 

Please advise.

**Comment by omerasif57** [comment]
re-installing the app with optional system reboot fixed the issue. Strange but anyway.

**Comment by omerasif57** [comment]
see issue #13
