### ISSUE TITLE
Show Image Detail On Wallpaper Not Working

### ISSUE THREAD

**Issue by smsali97** [keshavbhatt/BingWall#13]
Steps to Reproduce:

- After checking the 'Show Image Detail On Wallpaper' in Settings
- Click on any one of the wallpapers and they will not be downloaded.
- Uncheck  the 'Show Image Detail On Wallpaper' in Settings
- Wallpapers should now be downloaded

Can somebody please confirm, Thanks!

**Comment by keshavbhatt** [comment]
I was able to replicate the reported issue. 
Investigating the cause. A fix will arrive soon.
Thanks

**Comment by omerasif57** [comment]
System: Ubuntu 20.04.1

After fresh Install, App works fine i.e. setting wallpapers etc. But when you set Show Image Detail on Wallpaper settings, Set as Wallpaper action doesn't work.
