### ISSUE TITLE
Bingwall and wonderwall not running on Manjaro

### ISSUE THREAD

**Issue by HritwikSinghal** [keshavbhatt/BingWall#15]
- enabled snap support, and ran other snap apps successfully.
- install Bingwall and wonderwall, but both give following error

```
$ snap run wonderwall                                                                                              
Gtk-Message: 13:30:03.428: Failed to load module "canberra-gtk-module"
Gtk-Message: 13:30:03.443: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
QApplication: invalid style override passed, ignoring it.
Fontconfig warning: FcPattern object weight does not accept value [40 210)
zsh: segmentation fault (core dumped)  wonderwall

```

**Comment by keshavbhatt** [comment]
This is a known issue 
The solution that worked for many is  removing the system **fontconfig** cache and regenerate it with the following set of commands:
`sudo rm /var/cache/fontconfig/*`
`rm ~/.cache/fontconfig/*`
`fc-cache -r`

**Comment by keshavbhatt** [comment]
For reference : https://forum.snapcraft.io/t/snapped-app-not-loading-fonts-on-fedora-and-arch/12484/26

**Comment by HritwikSinghal** [comment]
still not working
