### ISSUE TITLE
Conflicts with AppArmour on Kubuntu/Ubuntu 20.04

### ISSUE THREAD

**Issue by scottbeamer** [keshavbhatt/BingWall#19]
Missing from settings, And when I try launching from the command line, this happens:

`bing-wall --set
Qt: Session management error: Could not open network socket
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.790\" (uid=1000 pid=29010 comm=\"bing-wall --set \" label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=682 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
`

**Comment by keshavbhatt** [comment]
The apply wallpaper feature will not work on KDE desktop, the app only works on Gnome based desktops.

**Comment by maroskukan** [comment]
I have the same issues on Ubuntu 20.04.

```bash
gnome-shell --version
GNOME Shell 3.36.9
Dgnome-shell --version
GNOME Shell 3.36.9
bing-wall --set
Gtk-Message: 08:02:45.984: Failed to load module "canberra-gtk-module"
Gtk-Message: 08:02:45.986: Failed to load module "canberra-gtk-module"
Qt: Session management error: Could not open network socket
QApplication: invalid style override passed, ignoring it.
propsReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.123\" (uid=1000 pid=3916 comm=\"bing-wall --set \" label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.DBus.Properties\" member=\"GetAll\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=971 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
nmReply "An AppArmor policy prevents this sender from sending this message to this recipient; type=\"method_call\", sender=\":1.123\" (uid=1000 pid=3916 comm=\"bing-wall --set \" label=\"snap.bing-wall.bing-wall (enforce)\") interface=\"org.freedesktop.NetworkManager\" member=\"GetDevices\" error name=\"(unset)\" requested_reply=\"0\" destination=\"org.freedesktop.NetworkManager\" (uid=0 pid=971 comm=\"/usr/sbin/NetworkManager --no-daemon \" label=\"unconfined\")"
"Object path cannot be empty"

```

**Comment by keshavbhatt** [comment]
sorry to inform you that, there is no backend implementation for any desktop environment other than gnome.
