### ISSUE TITLE
Feature Request: Use original resolution images instead of 1080p downscaled ones

### ISSUE THREAD

**Issue by pauldoo** [keshavbhatt/BingWall#20]
I use BingWall on my laptop with a 1080p display.  Often, but not always, I plug this laptop into a 4K external monitor and disable the laptop display.  If my external monitor isn't connected when BingWall refreshes, it'll scale the image down to 1080p and set my wallpaper to the scaled image.  This doesn't look great when I later connect the 4K external monitor as the 1080p image then looks blurry.

It would be great if BingWall _did not_ scale the downloaded image to match the resolution of the display, but instead set the wallpaper to the original resolution image leaving the desktop environment to handle scaling.  This would work better in environments where the monitor layouts change.

**Comment by pauldoo** [comment]
It actually appears that I now always get a 1080p image, regardless of which monitors I have connected.  I believe the cause of this is unrelated to the monitors, and perhaps a change in the peapix service which BingWall calls.

Looking at BingWall code found that the request for images is sent here: https://peapix.com/bing/feed?country=GB

The response is some JSON describing available images, where each image has a record like this example:

```
{
  "title": "Mount Fuji in Japan",
  "fullUrl": "https://img.peapix.com/cc373b4c8131476bb526471606f841c8_1080.jpg",
  "thumbUrl": "https://img.peapix.com/cc373b4c8131476bb526471606f841c8_480.jpg",
  "date": "2021-09-28",
  "pageUrl": "https://peapix.com/bing/36220"
}
```

Here the `fullUrl` is already a reference to a downsized 1080p image.  If I amend the URL and instead download `https://img.peapix.com/cc373b4c8131476bb526471606f841c8.jpg` (`_1080` removed), then I get the original resolution image (in this case 3351x1885.

---

It would be great if BingWall could adapt to this change in peapix and fetch the original resolution image instead of the 1080p one.

**Comment by keshavbhatt** [comment]
Thanks i will check it out.

**Comment by jcmagat** [comment]
Hi, I'm a new developer and a fan of this program. Is it cool if I take a crack at this? I'm thinking of adding a "Use full resolution" setting that fixes this issue

**Comment by pauldoo** [comment]
I had another peek at this, and the response from peapix.com has changed further.  I now see:

```
  {
    "title": "Manatee in Florida, USA",
    "fullUrl": "https://img.peapix.com/f9fcb300063145cfaa53c6fec692bff2_1080.jpg",
    "thumbUrl": "https://img.peapix.com/f9fcb300063145cfaa53c6fec692bff2_480.jpg",
    "imageUrl": "https://img.peapix.com/f9fcb300063145cfaa53c6fec692bff2.jpg",
    "date": "2021-11-15",
    "pageUrl": "https://peapix.com/bing/36700"
  },
```

The `imageUrl` field is the fullsize image (in this case 5084x2860), while `fullUrl` and `thumbUrl` are downsized images.  I think fixing this issue might be a simple case of replacing `"fullUrl"` with `"imageUrl"` in the BingWall code.

**Comment by keshavbhatt** [comment]
https://github.com/keshavbhatt/BingWall/commit/4bb455a62b2ce997f43cb3d0e5636dc93dae5e24 fixes this.

**Comment by jcmagat** [comment]
Ahh I was gonna do that but I thought getting the 1080p version was on purpose since the full resolution takes up much more storage. Anyways, if you want it as a optional setting #24  adds that, otherwise you could just close it

**Comment by keshavbhatt** [comment]
i will try your chnages. Thanks
