### ISSUE TITLE
I created AUR package for this

### ISSUE THREAD

**Issue by HritwikSinghal** [keshavbhatt/BingWall#21]
https://aur.archlinux.org/packages/bing-wall

Here is the link for AUR package. You can add that in readme. Now arch linux users can install via AUR. :)

**Comment by keshavbhatt** [comment]
thanks man i will add it soon.

**Comment by keshavbhatt** [comment]
https://github.com/keshavbhatt/BingWall/commit/31dc44a38021d852d949f3637eda68dedf4f92ff closes this
