### ISSUE TITLE
Object path cannot be empty

### ISSUE THREAD

**Issue by anh-viet-dang** [keshavbhatt/BingWall#25]
I using command
`
bing-wall --set
`
and i found a message
![image](https://user-images.githubusercontent.com/40136779/148551068-d5d9c3c8-df2e-46bc-9315-c7d11131f58d.png)

**Comment by keshavbhatt** [comment]
i will check.

**Comment by keshavbhatt** [comment]
Looks like app was not able to connect to internet while starting

**Comment by watson21** [comment]
I got a new desktop background after using this command. and my PC already connect to the internet. I think is just a wong message.

**Comment by lguerard** [comment]
Can reproduce the error using Linux Mint and I also got a new wallpaper.

![image](https://user-images.githubusercontent.com/6182107/151789806-d76f66ad-b806-4151-9971-819094c3ec55.png)

**Comment by dariuszmrugala** [comment]
I had a similar issue in Ubuntu 22.04.
BingWall was installed from the snap store. It needs to have appropriate privileges as below.
![image](https://user-images.githubusercontent.com/23068928/162053772-faaa0699-da8f-486d-ad3d-95f7a8e96946.png)

**Comment by keshavbhatt** [comment]
If there are no actual issues, these warnings can be ignored.
