### ISSUE TITLE
Open Download Folder option is not working anymore

### ISSUE THREAD

**Issue by krushnaj** [keshavbhatt/BingWall#27]
When I click on the **Open Download Folder** or go to Application Settings and then click on **Open Downloads** nothing happens.

It was working as expected opening the download location, but now it has stopped working. Not sure if this should happen.

BingWall Version: 2.0
OS: Ubuntu 20.04.4

**Comment by keshavbhatt** [comment]
I will check, i recently migrated to core20 snap base. That could be the reason.

**Comment by krushnaj** [comment]
Ok. Cheers.

**Comment by keshavbhatt** [comment]
This issue has been fixed in c8df5e93f1203709bfc2972fd3609a093648e3f1
Run to update to latest stable:
`snap refresh bing-wall`
