### ISSUE TITLE
dark scheme support doesn't work

### ISSUE THREAD

**Issue by dariuszmrugala** [keshavbhatt/BingWall#29]
Hi,

Thanks for considering my changes.

I updated today BingWall from snap in Ubuntu 22.04.
Unfortunately, changing images still don't work when Dark Scheme is chosen.

When I clone your repo and build it in qtcreator, it works.

From 'git log' I have:
![image](https://user-images.githubusercontent.com/23068928/162263444-dc4723e7-c7de-425a-9eb5-90119e3efffc.png)
and if I understand, my changes should be in the snap build. 

Have any idea what is the difference between my local build and snap package?

**Comment by keshavbhatt** [comment]
Your changes are in place, i think this is happening beacuse we have different version of gsettings in the runtime snap(it comes from core20). I tested your changes outside snap and they worked. I will test them on 20.04 and confirm.

**Comment by keshavbhatt** [comment]
Closed by da9191fd59a708e886f8fbf6a749fa1ca7dea7f9 (migrate to core22)

**Comment by keshavbhatt** [comment]
`snap refresh bing-wall`
will fix the issue.
