### ISSUE TITLE
appearance - dark style

### ISSUE THREAD

**Issue by Asem-D** [keshavbhatt/BingWall#31]
upgraded to ubuntu 22.04, using settings --> appearance --> dark style, BingWall does not set wallpaper. 
I believe the issue is in gsettings picture-uri, for dark theme it should be gsettings set org.gnome.desktop.background picture-uri-dark

**Comment by keshavbhatt** [comment]
Possible duplicates of #32 #29 
I am working on a soution.

**Comment by keshavbhatt** [comment]
Closed by da9191fd59a708e886f8fbf6a749fa1ca7dea7f9 (migrate to core22)
