### ISSUE TITLE
Since Ubuntu 22.04 upgrade, BingWall no longer sets the wallpaper

### ISSUE THREAD

**Issue by vergs72** [keshavbhatt/BingWall#32]
Since upgrading to Ubuntu 22.04 the 'Set Wallpaper' function does not change the desktop wallpaper. It downloads the wallpaper but doesn't actually change it, even if I select older downloaded wallpapers. What I have been doing to get around the issue is clicking on the 'Downloaded wallpaper' button, the clicking the folder open button, then right clicking the jpg file and choosing 'Set as wallpaper' from the pop-up menu.

**Comment by vergs72** [comment]
Just read some of the prior issues about the wallpaper not changing in Dark Mode, so I tested changing my appearance setting to Light Mode and then it does indeed work.

**Comment by keshavbhatt** [comment]
This require migrating to core22 base. I am working on it.

**Comment by keshavbhatt** [comment]
Closed by da9191fd59a708e886f8fbf6a749fa1ca7dea7f9 (migrate to core22)

**Comment by keshavbhatt** [comment]
`snap refresh bing-wall`
will fix the issue.
