### ISSUE TITLE
Add title of picture as text in bottom right corner

### ISSUE THREAD

**Issue by burni1337** [keshavbhatt/BingWall#4]
Hi!

First of all thank you for your great work, I love your application!

If you are still willing to develop from this stage, I would propose the following enhancement: 

It would be great if the title of the picture could also optionally appear on the wallpaper.

I believe it could be reasonably extracted because it appears to always be in the same div container:
`<div class="panel-overlay" style="position: absolute; z-index: 999; width: 938px; height: 24px; top: 0px; left: 0px; padding: 0px 10px; color: white; font-size: 1em;"><p>[20200406] - 'Cherry blossoms and Himeji Castle in Himeji, Japan (© Tororo/Getty Images)(Bing United States)'</p></div>`

**Comment by keshavbhatt** [comment]
You mean title of image as watermark ?

**Comment by burni1337** [comment]
yes

**Comment by keshavbhatt** [comment]
commit 550134bb closes this issue.

**Comment by burni1337** [comment]
Looks great! Thank you!

**Comment by keshavbhatt** [comment]
![Screenshot from 2020-04-15 00-23-42](https://user-images.githubusercontent.com/5965031/79262825-855c0b80-7eaf-11ea-9792-72a5eb5e45cd.png)
