### ISSUE TITLE
set as wallpaper "Ubuntu 20.04"

### ISSUE THREAD

**Issue by mahmoudtark25** [keshavbhatt/BingWall#9]
"set as wallpaper" doesn't work on Ubuntu 20.04. 
Suggestion: auto set "wallpaper of the day" will be a nice feature.

**Comment by keshavbhatt** [comment]
what desktop environment you using ? auto set wallpaper of the day works on every system restart for now.

**Comment by mahmoudtark25** [comment]
Thanks for your reply. I'm using Ubuntu 20.04 Gnome. But it's ok now, after reinstalling it the "set as wallpaper" became working without any problems.
And "set wallpaper of the day on System StartUp" is also working now but please add more locations especially my country Egypt. Thanks for this awesome app.

**Comment by omerasif57** [comment]
see issue #13

**Comment by keshavbhatt** [comment]
Will fix this in today's update.
